services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bowie
      POSTGRES_PASSWORD: vienna
      POSTGRES_DB: backend_db
    volumes:
      - menus-db-vol:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: luismsanchez808@gmail.com
      PGADMIN_DEFAULT_PASSWORD: vienna
    volumes:
      - admin-vol:/var/lib/pgadmin

volumes:
  menus-db-vol:
    external: true
  admin-vol:
    external: true