services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bowie
      POSTGRES_PASSWORD: vienna
      POSTGRES_DB: backend_db
    networks:
      - app-network
    volumes:
      - menus-db-vol:/var/lib/postgresql/data 
  
  app:
    build: .
    container_name: node-app
    environment:
      - DATABASE_URL=postgresql://bowie:vienna@db:5432/backend_db?schema=public
      - JWT_SECRET=68xpTyyOCn+j9DfMBra13sD69iOjRiYzvt4UCosbgZY=
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

volumes:
  menus-db-vol:
    external: true
  admin-vol:
    external: true

networks:
  app-network:
    driver: bridge